FROM ubuntu:18.04

RUN apt update && apt install --no-install-recommends -y \
        build-essential \
        cmake \
        gfortran \
        git \
        libopenmpi-dev \
        openmpi-bin \
        openssh-client \
        libfftw3-dev \
        libfftw3-mpi-dev \
        python3 \
        python3-numpy \
        python3-mpi4py \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
